# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define() do

  create_table "people", :id => false, :force => true do |t|
    t.column "first_name", :string
    t.column "last_name",  :string
    t.column "ssn",        :string, :limit => 64
  end

  create_table "places", :id => false, :force => true do |t|
    t.column "address", :text
    t.column "city",    :string
    t.column "state",   :string
    t.column "country", :string, :limit => 2
  end

  create_view "v_person", "SELECT people.first_name AS f_name, people.last_name AS l_name, people.ssn AS social_security FROM people;", :force => true do |v|
    v.column :f_name
    v.column :l_name
    v.column :social_security
  end

end
